name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dec759291fac870a533b3014205f8280b5002a93260c30ae26c993dd5d16dcc7"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
