name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b38d0528057808bc343fd9caf248990fc4a466cd29b82b51377fcde71aaba530"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
