name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b116ab7880e8538b1836ed47ddce63b83f450feb96e53cba8b85a65c96e7d035"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
