name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9a8d9016e9542bab7354ff31947b1b219845f88c65c92bd0028346d1d1a2cf2"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
