name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed5b42ad79e6209bde2a936d5bd0923ccb6a5430430e5a1dfc48fcf64b049446"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
