name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c1c5823a0a396ad3f5dfe4149935663eb5c5ccba23a2434fac81c99bf77547d"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
