name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5a010ad942ebc057fb7de6702009fa3ba10876fb2d543fac0658e44deb89ba6"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
