name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bf122be5427dcb4ff26659ec5e163785c606eacd1b84bf3b8e998b05e3523b7"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
