name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "943fe57a810dcdb8cee47a5d6aad35e85cff445416bb0fbf56edff5faa2b8365"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
