name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "297e5330e38b4a716595455bccceca946d20842c9af35c431dd3317e2d8585c0"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
