name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a10da03263368459ccf5882548538dc792beedfe234fde0bdba69ef1114bb67d"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
