name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98643bf1c0b3618156584986f0e19fdbf6e3cf969efcbe72d050afadfde80d20"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
