name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9a179a98a96a823643c6bd360a213aa400af9e8d91be30060b3542c1814d1a1"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
