name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee7dee972f8c23375c1912f6eff38804cd4653617115799a57283bf0c92664ea"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
