name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "425d08863e5fa39717e21d00b1a22e24ea7c5b06f4e696966236e9d54819beb9"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
