name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49ab1a0a4352d4124ce35d8161c4e3e2fdd5a5993535b2a3e56bbb27b3e2aacf"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
