name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2be9a1882781a153d1dabe5f28af5df2bff836fbe8a2b48331724ce0377bb498"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
