name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49d5770849e07e4d0ff01689444f788438830e15e795ecf485303fb28911601d"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
