name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "546dc7b5ae150ba9ad25d6ebb4d735bf06d93e3374b6fec67a445870221f7286"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
