name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47281724cd3b4f10459b1eb0001cd6d9a42ddc3ff3565b8eab88a0dd8c74104c"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
