name = "DragonCraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea576fda3cda832d01c8096cfb14822391e3dd5e4faa10f394eb6abbe3223db1"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
