name = "Fabric API"
filename = "fabric-api-0.42.0+1.17.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.42.0+1.17/fabric-api-0.42.0+1.17.jar"
hash-format = "sha512"
hash = "80f68a1a6cd63ccde07784c4d6030776079963260aff3574d25f4715e8dfffc8dea25b8cffc0fc0f22d5cddfbd21cf447fa2f5f7fc7e85efe1696c1c2366660f"

[update]
[update.modrinth]
mod-id = "P7dR8mSH"
version = "cCwCSFzJ"
